### ISSUE TITLE
Broken on Apple Silicon

### ISSUE THREAD

**Issue by Esgrove** [supermihi/pytaglib#121] opened 2023-11-20 09:32 UTC
Can't use on Apple Silicon. Works on Windows and Intel Mac but fails on M1:

```shell
Traceback (most recent call last):
  File "/opt/homebrew/bin/pyprinttags", line 5, in <module>
    from pyprinttags import script
  File "/opt/homebrew/lib/python3.11/site-packages/pyprinttags.py", line 18, in <module>
    import taglib
ImportError: dlopen(/opt/homebrew/lib/python3.11/site-packages/taglib.cpython-311-darwin.so, 0x0002): symbol not found in flat namespace '__ZN6TagLib10StringList6appendERKNS_6StringE'
```

```
Traceback:
/opt/homebrew/Cellar/python@3.12/3.12.0/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py:90: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
test_renamer.py:5: in <module>
    from renamer import Renamer
renamer.py:9: in <module>
    import taglib
E   ImportError: dlopen(/Users/akseli/Library/Caches/pypoetry/virtualenvs/track-ranamer-7z4fB1tm-py3.12/lib/python3.12/site-packages/taglib.cpython-312-darwin.so, 0x0002): symbol not found in flat namespace '__ZN6TagLib10StringList6appendERKNS_6StringE'
```

**Comment by Esgrove** [comment] 2023-11-21 10:52
Tried building manually, which fails too. Might be related to Xcode 15 🤔 I am on macOS Sonoma 14.1.1.

```shell
Processing /Users/akseli/Developer/pytaglib
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: pytaglib
  Building wheel for pytaglib (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for pytaglib (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [28 lines of output]
      warning: src/ctypes.pxd:65:0: The 'IF' statement is deprecated and will be removed in a future Cython version. Consider using runtime conditions or C macros instead. See https://github.com/cython/cython/issues/4310
      [1/1] Cythonizing src/taglib.pyx
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-14-arm64-cpython-311
      copying src/pyprinttags.py -> build/lib.macosx-14-arm64-cpython-311
      running egg_info
      writing src/pytaglib.egg-info/PKG-INFO
      writing dependency_links to src/pytaglib.egg-info/dependency_links.txt
      writing entry points to src/pytaglib.egg-info/entry_points.txt
      writing requirements to src/pytaglib.egg-info/requires.txt
      writing top-level names to src/pytaglib.egg-info/top_level.txt
      reading manifest file 'src/pytaglib.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      adding license file 'LICENSE.txt'
      writing manifest file 'src/pytaglib.egg-info/SOURCES.txt'
      running build_ext
      building 'taglib' extension
      creating build/temp.macosx-14-arm64-cpython-311
      creating build/temp.macosx-14-arm64-cpython-311/src
      clang -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk -I/Users/akseli/Developer/pytaglib/build/taglib/Darwin-x64-py3.11.6/include -I/opt/homebrew/opt/python@3.11/Frameworks/Python.framework/Versions/3.11/include/python3.11 -c src/taglib.cpp -o build/temp.macosx-14-arm64-cpython-311/src/taglib.o
      src/taglib.cpp:1246:10: fatal error: 'taglib/tstring.h' file not found
      #include "taglib/tstring.h"
               ^~~~~~~~~~~~~~~~~~
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pytaglib
Failed to build pytaglib
ERROR: Could not build wheels for pytaglib, which is required to install pyproject.toml-based projects
```

**Comment by Esgrove** [comment] 2023-11-21 11:12
Tried passing the include dirs with 
```
pip install --global-option="-I$(brew --prefix)/include/" --global-option="-L$(brew --prefix)/lib" .

Building wheels for collected packages: pytaglib
  WARNING: Ignoring --global-option when building pytaglib using PEP 517
```

Then after some investigation, tried this:

```shell
pip install --config-settings="-I$(brew --prefix)/include/" --config-settings="-L$(brew --prefix)/lib" .
```

and

```shell
C_INCLUDE_PATH=$(brew --prefix)/include CPLUS_INCLUDE_PATH=$(brew --prefix)/include LD_LIBRARY_PATH=$(brew --prefix)/lib pip install .

...

      clang -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk -I/Users/akseli/Developer/pytaglib/build/taglib/Darwin-x64-py3.11.6/include -I/opt/homebrew/opt/python@3.11/Frameworks/Python.framework/Versions/3.11/include/python3.11 -c src/taglib.cpp -o build/temp.macosx-14-arm64-cpython-311/src/taglib.o
      clang++ -bundle -undefined dynamic_lookup -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk build/temp.macosx-14-arm64-cpython-311/src/taglib.o -L/Users/akseli/Developer/pytaglib/build/taglib/Darwin-x64-py3.11.6/lib -L/Users/akseli/Developer/pytaglib/build/taglib/Darwin-x64-py3.11.6/lib64 -ltag -o build/lib.macosx-14-arm64-cpython-311/taglib.cpython-311-darwin.so
      ld: warning: search path '/Users/akseli/Developer/pytaglib/build/taglib/Darwin-x64-py3.11.6/lib' not found
      ld: warning: search path '/Users/akseli/Developer/pytaglib/build/taglib/Darwin-x64-py3.11.6/lib64' not found
      ld: library 'tag' not found
```

**Comment by supermihi** [comment] 2023-11-22 07:14
looks like a duplicate of #114

**Comment by supermihi** [comment] 2023-11-22 07:18
continuing the discussion there

**Closed by supermihi** 2023-11-22 07:18 UTC
