### ISSUE TITLE
Build test fails on macos-latest with Python 3.10

### ISSUE THREAD

**Issue by Popkornium18** [supermihi/pytaglib#105] opened 2022-06-28 17:38 UTC
I noticed that the build test startet failing on macos-latest with Python 3.10: [Example](https://github.com/Popkornium18/pytaglib/runs/7097985153)

I'm not sure if that is an issue with the test or if it actually won't compile on a real machine.

**Comment by supermihi** [comment] 2022-06-28 18:49
I can confirm that it fails. Tried switching to macos-12 (arm64) but there the situation looks even worse. :-/ Because I'm not a mac OS user, I have no idea how to debug or fix this.

**Comment by Popkornium18** [comment] 2022-06-29 09:24
I'm not a mac user either, unfortunately. I just noticed that the tests of my application built on pytaglib started failing. I have disabled the test for now. Maybe one could run mac OS in a VM to debug this. It's not as easy as installing Linux or Windows in a VM but it is possible afaik.

**Comment by strayer** [comment] 2022-07-04 18:12
I found a (very *VERY* hacky) workaround for this… the issue is that for some reason GCC used by macOS 11 and Python 3.10 doesn't look up includes and libraries in /usr/local/include|lib anymore. I don't really understand why this is working for Python<3.10 and there may very well be a much cleaner fix, but hey… it works.

I noticed that GCC is being told to search for includes and libs in /usr/local/opt/sqlite/, so I added a step to copy over taglibs files there:

```
- name: Fix TagLib on macOS 11 with Python 3.10
        if: matrix.os == 'macos-latest' && matrix.python-version == '3.10'
        run: |
          rsync -avP $(brew --prefix taglib)/include/ /usr/local/opt/sqlite/include/
          rsync -avP $(brew --prefix taglib)/lib/ /usr/local/opt/sqlite/lib/
```

Again, its a really ugly hack, but for testing runs I find it fine for the time being.

Note that it is possible to tell pip to add the correct parameters to GCC: https://stackoverflow.com/questions/18783390/python-pip-specify-a-library-directory-and-an-include-directory

`pip install --global-option=build_ext --global-option="-I/usr/local/include/" --global-option="-L/usr/local/lib"  <you package name>`

I didn't try this because the project I was working on is poetry, which doesn't expose these options.

A test run that utilizes this hack: https://github.com/iscc/iscc-sdk/runs/7185159802?check_suite_focus=true

https://github.com/iscc/iscc-sdk/pull/62

**Comment by queengooborg** [comment] 2022-08-21 15:43
Thanks @strayer -- I can confirm that manually specifying the `taglib` dirs with the arguments did the trick on my end.  Seeing as I'm now using an M1 MacBook Pro, this makes sense, since Homebrew installs packages to a different location on ARM macOS (`/opt/homebrew` instead of `/usr/local`).

I imagine a fix could be to add an `elif` clause [here](https://github.com/supermihi/pytaglib/blob/39aabb26f4d6016c110794361b20b7fb76e64ecc/setup.py#L53) for macOS users, that also adds Homebrew on ARM's path.  I'd be happy to write a pull request for this, if that sounds good to you @supermihi!

**Comment by supermihi** [comment] 2022-08-22 07:42
@queengooborg I would be very happy about such a PR, thank you!

**Comment by SheepYY039** [comment] 2022-10-13 08:34
> (`/opt/homebrew` instead of `/usr/local`)

Adding on to @queengooborg, for others who are experiencing this issue, the command that worked for me is 
```bash 
 pip install --global-option=build_ext --global-option="-I/opt/homebrew/include/" --global-option="-L/opt/homebrew/lib" pytaglib
```

**Comment by supermihi** [comment] 2023-03-26 11:50
Hi everyone,
I just merged a PR that switches to [cibuildwheel](https://cibuildwheel.readthedocs.io/en/stable/) for building wheels. Not sure if that is the reason, but anway there are no longer any compile errors, and I've successfully uploaded a [bunch of MacOS wheels](https://pypi.org/project/pytaglib/#files) to PyPI.

**Closed by supermihi** 2023-03-26 11:50 UTC

**Comment by supermihi** [comment] 2023-03-26 11:53
Thinking about it, the root cause for the fix most probably is that we now compile & link our self-built native taglib, instead of relying on the system-wide installation by brew.
