### ISSUE TITLE
warning: 'OSAtomicDecrement32Barrier' is deprecated: first deprecated in macOS 10.12 

### ISSUE THREAD

**Issue by mickaelmonsieur** [supermihi/pytaglib#41] opened 2018-02-08 16:15 UTC
Hi,
I try to install on Mac Os High Sierra.
I have this error:

```
sudo pip install pytaglib
The directory '/Users/mickael/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/mickael/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting pytaglib
  Downloading pytaglib-1.4.2.tar.gz (110kB)
    100% |████████████████████████████████| 112kB 1.7MB/s 
Requirement already satisfied: Cython in /Library/Python/2.7/site-packages (from pytaglib)
Installing collected packages: pytaglib
  Running setup.py install for pytaglib ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-LjP4xM/pytaglib/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-9IFkyQ-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.13-intel-2.7
    copying src/pyprinttags.py -> build/lib.macosx-10.13-intel-2.7
    running build_ext
    building 'taglib' extension
    creating build/temp.macosx-10.13-intel-2.7
    creating build/temp.macosx-10.13-intel-2.7/src
    cc -fno-strict-aliasing -fno-common -dynamic -arch x86_64 -arch i386 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch i386 -arch x86_64 -pipe -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c src/taglib.cpp -o build/temp.macosx-10.13-intel-2.7/src/taglib.o
    In file included from src/taglib.cpp:574:
    In file included from /usr/local/include/taglib/tstringlist.h:30:
    In file included from /usr/local/include/taglib/tlist.h:263:
    In file included from /usr/local/include/taglib/tlist.tcc:27:
    /usr/local/include/taglib/trefcounter.h:83:18: warning: 'OSAtomicIncrement32Barrier' is deprecated: first deprecated in macOS 10.12 - Use std::atomic_fetch_add() from <atomic> instead [-Wdeprecated-declarations]
        void ref() { OSAtomicIncrement32Barrier(const_cast<int32_t*>(&refCount)); }
                     ^
    /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/libkern/OSAtomicDeprecated.h:182:9: note: 'OSAtomicIncrement32Barrier' has been explicitly marked deprecated here
    int32_t OSAtomicIncrement32Barrier( volatile int32_t *__theValue );
            ^
    In file included from src/taglib.cpp:574:
    In file included from /usr/local/include/taglib/tstringlist.h:30:
    In file included from /usr/local/include/taglib/tlist.h:263:
    In file included from /usr/local/include/taglib/tlist.tcc:27:
    /usr/local/include/taglib/trefcounter.h:84:29: warning: 'OSAtomicDecrement32Barrier' is deprecated: first deprecated in macOS 10.12 - Use std::atomic_fetch_sub() from <atomic> instead [-Wdeprecated-declarations]
        bool deref() { return ! OSAtomicDecrement32Barrier(const_cast<int32_t*>(&refCount)); }
                                ^
    /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/libkern/OSAtomicDeprecated.h:201:9: note: 'OSAtomicDecrement32Barrier' has been explicitly marked deprecated here
    int32_t OSAtomicDecrement32Barrier( volatile int32_t *__theValue );
            ^
    src/taglib.cpp:1736:41: error: cannot initialize a parameter of type 'FileName' (aka 'const char *') with an lvalue of type 'const Py_UNICODE *' (aka 'const unsigned short *')
        __pyx_t_6 = TagLib::FileRef::create(__pyx_t_5);
                                            ^~~~~~~~~
    /usr/local/include/taglib/fileref.h:273:34: note: passing argument to parameter 'fileName' here
        static File *create(FileName fileName,
                                     ^
    2 warnings and 1 error generated.
    error: command 'cc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-LjP4xM/pytaglib/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-9IFkyQ-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-build-LjP4xM/pytaglib/
```

**Comment by supermihi** [comment] 2018-02-27 16:45
The warning is not the problem here, bit the error in the next line. This is actually a duplicate of #42 and #43 and is fixed with version 1.4.3.

**Closed by supermihi** 2018-02-27 16:45 UTC
