### ISSUE TITLE
empty tag not saved for FLAC files

### ISSUE THREAD

**Issue by drtebi** [supermihi/pytaglib#19] opened 2016-05-08 13:38 UTC
For some reason the 'COMMENT' tag is not saved:

> > > import taglib
> > > s = taglib.File('Al Dimeola, John McLaughlin, Paco De Lucia - 03 - Frevo Rasgado.flac')
> > > s.tags
> > > {'GENRE': ['Jazz'], 'TITLE': ['Frevo Rasgado'], 'DATE': ['1981'], 'COMMENT': ['Track 3'], 'ARTIST': ['Al Dimeola, John McLaughlin, Paco De Lucia'], 'TRACKNUMBER': ['03'], 'ALBUM': ['Friday Night In San Francisco']}
> > > s.tags['COMMENT'] = ['']
> > > s.tags
> > > {'GENRE': ['Jazz'], 'TITLE': ['Frevo Rasgado'], 'DATE': ['1981'], 'COMMENT': [''], 'ARTIST': ['Al Dimeola, John McLaughlin, Paco De Lucia'], 'TRACKNUMBER': ['03'], 'ALBUM': ['Friday Night In San Francisco']}
> > > s.save()
> > > {}
> > > s.tags
> > > {'GENRE': ['Jazz'], 'TITLE': ['Frevo Rasgado'], 'DATE': ['1981'], 'COMMENT': [''], 'ARTIST': ['Al Dimeola, John McLaughlin, Paco De Lucia'], 'TRACKNUMBER': ['03'], 'ALBUM': ['Friday Night In San Francisco']}
> > > s.close()
> > > s = taglib.File('Al Dimeola, John McLaughlin, Paco De Lucia - 03 - Frevo Rasgado.flac')
> > > s.tags
> > > {'GENRE': ['Jazz'], 'TITLE': ['Frevo Rasgado'], 'DATE': ['1981'], 'COMMENT': ['Track 3'], 'ARTIST': ['Al Dimeola, John McLaughlin, Paco De Lucia'], 'TRACKNUMBER': ['03'], 'ALBUM': ['Friday Night In San Francisco']}

This appears to happen only with .flac files. Would be great if someone could look into it...

**Comment by drtebi** [comment] 2016-05-08 21:27
A it more info... as I see that this has been a problem before with an older taglib library.

I am using taglib 1.11, so I assume the problem must have re-appeared.

The problem does however only happen when I try to set the COMMENT tag to an empty list. Maybe that has something to do with it.

**Comment by supermihi** [comment] 2016-05-09 06:54
Hit @drtebi ,
thanks for your report. Could you please check if this affects other (flac) files and/or other tags as well?
Note also that the correct way to remove the comment tag would be to either `del s.tags['COMMENT']` or `s.tags['COMMENT'] = []`. What you do is set the comment to an empty string, I could imagine that this causes problems (of course, it's still a bug).

Michael

**Comment by drtebi** [comment] 2016-05-09 13:27
Thanks for the quick response.

I have only tried flac and mp3 files, and this bug appears to only affect flac files.

These other tags I have tested and are not affected:
ARTIST, ALBUM ARTIST, DATE, GENRE, STYLE, LANGUAGE

It hasn't occured to me to use [] instead of ['']... I just used whatever was set in a QLineEdit field. I will test that and report back if it works. Would definitely be better than my current solution, adding a a single space...

**Comment by drtebi** [comment] 2016-05-09 23:12
I have just tested again, with a couple of different FLAC files.

It is really strange... because somehow the file seems to have a memory. Here is what happened:

Opened file, set COMMENT to ' ' (empty space), saved file, closed file.
Opened file, now COMMENT is ' ' (empty space)

Set COMMENT to [] (empty list), saved file, closed file.
Opened file, now COMMENT is 'TRACK 3' !!

Deleted COMMENT (del s.tags['COMMENT']), saved file, closed file.
Opened file, now COMMENT is 'TRACK 3' !!

Really strange. I assume that there is some hidden tag that causes the COMMENT field to be populated with the track number when COMMENT it is empty? 

This appears to happen every time when I delete a COMMENT tag, whether I use 'del', an empty list, or a list with a empty string element. Then the COMMENT tag magically becomes 'TRACK X' (X being its track number).

Very strange indeed. The only work-around for now is to set COMMENT to an empty space.

**Comment by drtebi** [comment] 2016-05-16 02:45
I just noticed that the same thing happens with the DATE field, on FLAC files.

Any chances that this could be fixed? I would greatly appreciate it.

**Comment by supermihi** [comment] 2016-05-17 07:07
I hope to find some time next weekend to investigate the issue. It's most probably a problem with taglib itself, as pytaglib simply wraps the taglib API – there's no special handling of specific tags such as DATE or COMMENT in pytaglib itself.

I'll report any progress here.
Michael

**Comment by drtebi** [comment] 2016-05-17 22:27
Thank you for looking into it. I assume that the same problem may exist with other tags, I probably haven't noticed since my other tags usually had values as opposed to being empty.

It's very likely that the problem is taglib related. I looked a bit at the pytaglib source code, I did not notice anything there that could cause this problem, but then again, I am not very familiar with extensions.

Meanwhile I have been fiddling with mutagen. It does work, but is also a lot more trouble to implement. pytaglib would be much simpler...

P.S.: I renamed the topic, since it is not just related to the COMMENT field.

**Comment by supermihi** [comment] 2016-05-22 10:26
I am not able to reproduce your issue with my own FLAC files (see the unit test I have just commited). I'm also using taglib-1.11 so this shouldn't be the problem.

You might be affected by https://github.com/taglib/taglib/issues/646. Do you have a way to check if your FLAC files contain ID3 tags instead of normal vorbis comments? Otherwise, could you send me an example file?

**Comment by drtebi** [comment] 2016-05-27 02:14
Sorry for the delay.
I checked the file (the same I used in my original post here), and using 'file' it turns out it indeed has ID3 tags:
`
file "Al Dimeola, John McLaughlin, Paco De Lucia - 03 - Frevo Rasgado.flac" 
Al Dimeola, John McLaughlin, Paco De Lucia - 03 - Frevo Rasgado.flac: Audio file with ID3 version 2.4.0, contains: FLAC audio bitstream data, 16 bit, stereo, 44.1 kHz, 20829900 samples
`
So that appears to be the problem then. The question now is, how can I get rid of the ID3 tags? I tried using `f.removeUnsupportedProperties()`, but it complained with `TypeError: removeUnsupportedProperties() takes exactly one argument (0 given)`.

Does taglib have a way to remove the ID3 tags?

**Comment by supermihi** [comment] 2016-08-18 07:11
Hi again,
could you perhaps send me one of the files affected? I'd like to try to debug what's happening here under the hood.

**Comment by supermihi** [comment] 2016-11-27 18:20
Sorry for the quite long delay. I finally found the reason for this bug (which is indeed inside taglib itself). There's an open [pull request](https://github.com/taglib/taglib/pull/779) that should fix the issue. If you'r eager you can try to compile the patched taglib version by yourself, otherwise it will hopefully be fixed in the next release.

**Comment by supermihi** [comment] 2016-11-27 18:21
Closing the `pytaglib` issue as it's not a bug in this project.

**Closed by supermihi** 2016-11-27 18:21 UTC

**Comment by drtebi** [comment] 2016-11-28 22:30
Sounds good! I will definitely check it out when I work on my application again.
