### ISSUE TITLE
'taglib/tstring.h' file not found

### ISSUE THREAD

**Issue by OdinTech3** [supermihi/pytaglib#32] opened 2017-03-09 03:27 UTC
Everytime I try to install the pytaglib module using pip I get this error:

```
src/taglib.cpp:437:10: fatal error: 'taglib/tstring.h' file not found
#include "taglib/tstring.h"
         ^
1 error generated.
error: command 'cc' failed with exit status 1
```

When I check the [source](https://pypi.python.org/packages/8c/31/3a985f9b32295f3a146bd4e9cda2287fc0dd6d7a8837ad01588299d6ad4f/pytaglib-1.4.0.tar.gz#md5=4b2a50687061f77deb184e3fa8850806) from pypi package index, didn't any such file.

**Comment by supermihi** [comment] 2017-03-09 09:27
This is most probably a duplicate of  #15  – please ensure that you have taglib with dev headers installed on your system!

**Closed by supermihi** 2017-03-09 09:27 UTC
