### ISSUE TITLE
m4a files use aART tag for album artist. pytaglib returns this as an unsupported tag.

### ISSUE THREAD

**Issue by rhthorpe** [supermihi/pytaglib#46] opened 2018-05-21 15:29 UTC
Reopening this. I am now running 1.4.3 of pytaglib on Ubuntu 13.04. pyprinttags3 gives the following output.
roger@roger-pc:~$ pyprinttags3 '/home/roger/Music/Handel, George Frideric/Messiah, HWV 56/Higginbottom, Edward/m4a/40 He that dwelleth in Heaven shall laugh them to scorn.m4a' 
*********************************************************************
TAGS OF '40 He that dwelleth in Heaven shall laugh them to scorn.m4a'
*********************************************************************
ARTIST      = Academy of Ancient Music/Choir of New College, Oxford/Jenkinson, Henry (Treble)/Jones, Otta (Treble)/Brooks, Robert (Treble)/Davies, Iestyn (Countertenor)/Spence, Toby (Tenor)/Dougan, Eamonn (Bass)/Higginbottom, Edward
COMPOSER    = Handel, George Frideric
GENRE       = m4a
TRACKNUMBER = 40/52
ALBUM       = Messiah, HWV 56
DATE        = 1741
TITLE       = 40 He that dwelleth in Heaven shall laugh them to scorn
Unsupported tag elements: aART
remove unsupported properties? [yN] n
roger@roger-pc:~$

m4a file included below.
puddletag shows album artist as Higginbottom, Edward
[40 He that dwelleth in Heaven shall laugh them to scorn.m4a.zip](https://github.com/supermihi/pytaglib/files/2023123/40.He.that.dwelleth.in.Heaven.shall.laugh.them.to.scorn.m4a.zip)

**Comment by supermihi** [comment] 2018-06-06 05:48
Thanks for reporting this. I'll have a look asap. Presumably it is an issue within taglib, in the property map implementation for m4a files.

**Comment by supermihi** [comment] 2018-08-26 16:33
Sorry for the delay. It does work on my system. What version of taglib do you have installed? 

Duplicate of #34. Adding a unit test.

**Closed by supermihi** 2018-08-26 16:33 UTC

**Comment by supermihi** [comment] 2018-08-26 19:03
Update: It *does* fail on the travis build server, which is using taglib-1.9. I do not have the issue with taglib-1.11, so I assume it was fixed in taglib between those versions.

**Comment by supermihi** [comment] 2018-10-31 15:55
Yes, I noticed the same a few days ago. Seems not completely trivial to install a more recent taglib version, so I decided to wait until travis updates to a newer Ubuntu release.

**Comment by vinyldarkscratch** [comment] 2018-11-01 23:09
I just got a response from them, and they stated that it's in the works, though they're not sure when it'll be ready:

> You're right, at the moment we do not support Ubuntu 16.04 Xenial as one of our base images. It's currently on our roadmap, but I'm afraid I do not have an ETA for when this will happen, here's the GitHub issue tracking it https://github.com/travis-ci/travis-ci/issues/5821 that we'll make sure to re-open when Xenial is available in Travis CI.

They did give us a recommendation on what to do in the meantime, though:

> That said, I'd definitely recommend using Docker in your builds pulling the Ubuntu 16.04 Xenial image from Docker Hub: https://hub.docker.com/_/ubuntu/ to run your tests in Ubuntu 16.04
>
> For example, here's the PR that enabled it for Rust: https://github.com/rust-lang/rust/pull/34016/files, is this something you'd be interested in trying out?

**Comment by ardumont** [comment] 2019-03-09 08:50
That test is failing for me because the test reference an issue46.m4a file which does not exist.

```
    def copyfile(src, dst, *, follow_symlinks=True):
        """Copy data from src to dst.

        If follow_symlinks is not set and src is a symbolic link, a new
        symlink will be created instead of copying the file it points to.

        """
        if _samefile(src, dst):
            raise SameFileError("{!r} and {!r} are the same file".format(src, dst))

        for fn in [src, dst]:
            try:
                st = os.stat(fn)
            except OSError:
                # File most likely does not exist
                pass
            else:
                # XXX What about other special files? (sockets, devices...)
                if stat.S_ISFIFO(st.st_mode):
                    raise SpecialFileError("`%s` is a named pipe" % fn)

        if not follow_symlinks and os.path.islink(src):
            os.symlink(os.readlink(src), dst)
        else:
>           with open(src, 'rb') as fsrc:
E           FileNotFoundError: [Errno 2] No such file or directory: '/tmp/nix-build-python3.7-pytaglib-1.4.4.drv-0/pytaglib-1.4.4/tests/data/issue46.m4a'

/nix/store/gbwx5sc4w0i0ipnmsa0nsk88svs983vl-python3-3.7.2/lib/python3.7/shutil.py:120: FileNotFoundError
===================== 1 failed, 18 passed in 0.44 seconds ======================
```

Indeed, the file is not part of the pypi release..
```
tar xvf pytaglib-1.4.4.tar.gz | grep data
pytaglib-1.4.4/tests/data/
pytaglib-1.4.4/tests/data/issue19.flac
pytaglib-1.4.4/tests/data/onlyv1.mp3
pytaglib-1.4.4/tests/data/r2.mp3
pytaglib-1.4.4/tests/data/rare_frames.mp3
pytaglib-1.4.4/tests/data/readönly.mp3
pytaglib-1.4.4/tests/data/testöü.flac
pytaglib-1.4.4/tests/data/Жбж.mp3
```

But it is present in the git tree...

Ok, i blame the MANIFEST.in which misses the pattern for `.m4a` file [1]

[1] https://github.com/supermihi/pytaglib/blob/master/MANIFEST.in#L7

Cheers,
