### ISSUE TITLE
pytaglib by default give only year and not complete date that is tagged with mp3 files

### ISSUE THREAD

**Issue by varun952** [supermihi/pytaglib#61] opened 2019-04-04 11:49 UTC
<code>import taglib</code>
<code>song = taglib.File("hawkeye_090.mp3")</code>
<code>song.tags</code>
OutPut: 
{u'ALBUM': [u'Telugu Stream 5th Anniversary'], u'ARTIST': [u'Radio Sai'], u'GENRE': [u'devotional, radio, spiritual'], u'ALBUMARTIST': [u'Radio Sai'], u'DATE': [u'2016'], u'TRACKNUMBER': [u'3']}

Following is All tagged information in this file :
--------------------------------------------------
Time: 36:52	MPEG2, Layer III	[ 24 kb/s @ 22050 Hz - Mono ]
--------------------------------------------------------------------------------------------------------------------------------
ID3 v2.3:
title: 
artist: Radio Sai
album: Telugu Stream 5th Anniversary
album artist: Radio Sai
recording date: **2016-07-24**
track: 3		genre: devotional, radio, spiritual (id None)
FRONT_COVER Image: [Size: 51450 bytes] [Type: image/jpeg]
Description: 

PRIV: [Data: 4660 bytes]
Owner Id: XMP

**Comment by varun952** [comment] 2019-04-11 11:47
Any updated regarding this issue?

**Comment by supermihi** [comment] 2019-04-11 18:18
Which software is giving you the second output?

**Comment by varun952** [comment] 2019-04-11 18:19
For command line I am using eyeD3

**Comment by supermihi** [comment] 2019-04-11 18:56
Might be an additional ID3v1 tag with conflicting information. Could you send me a copy of the file for testing?

**Comment by varun952** [comment] 2019-04-15 06:15
Please get the file as you requested : 
https://drive.google.com/file/d/1smdwyTVqdmrg5QAIGu5Gg3rs0_3mq0Gq/view?usp=sharing

**Comment by varun952** [comment] 2019-04-15 06:16
I look forward to your comments

**Comment by supermihi** [comment] 2019-04-16 13:46
It works for me:
```python
>>> import taglib
>>> f = taglib.File("vv.mp3")
>>> f.tags
{'ALBUM': ['Sathya Sai Speaks'], 'ARTIST': ['Bhagawan Sri Sathya Sai Baba'], 'COMMENT': ['I am no good'], 'COPYRIGHT': ['www.radiosai.org'], 'DATE': ['1986-11-21'], 'GENRE': ['Discourse'], 'LABEL': ['www.radiosai.org'], 'TITLE': ['Village service and pre-requisites needed for it']}
```
Could you be using an outdated version of taglib? There used to be some issues with ID3 v1→v2 conversion earlier.

**Comment by varun952** [comment] 2019-04-16 14:09
Ok, i will verify once, I installed version 1.4.5

**Comment by varun952** [comment] 2019-04-16 14:12
Sir , i verified once again with latest version 1.4.5 it gives me year not complete date with same file which I send you

**Comment by supermihi** [comment] 2019-04-16 20:15
Sorry for being unclear; I was refering to the version of [taglib](https://taglib.github.io) that is used by pytaglib. If you're on linux, you can get the version with `taglib-config --version`.

**Comment by varun952** [comment] 2019-04-17 07:46
Taglib version is 1.9.1

**Comment by supermihi** [comment] 2019-04-17 18:55
Thank you. That is most probably the cause; I remember some issues prior to taglib 1.11. Do you have any chance to update taglib?
I am going to close this issue as it is not related to pytaglib itself but the underlying taglib library.

**Closed by supermihi** 2019-04-17 18:55 UTC
